name: DisneyCodeChallenge_JamieWilliams
description: "AFlutter Coding Challenge"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  json_annotation: ^4.9.0
  go_router: ^14.2.2
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.0
  uuid: ^4.4.2
  google_fonts: ^6.2.1
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  json_serializable: ^6.8.0



flutter:
        uses-material-design: true
    